version: '3.8'
services:
  mongo:
    image: mongo:7
    networks:
      - chatbot-network
    volumes:
      - mongo_data:/data/db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: chatbot-backend:latest
    env_file:
      - ./backend/.env
    networks:
      - chatbot-network
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: chatbot-frontend:latest
    environment:
      - NODE_ENV=development
      - VITE_API_URL=backend:5001/api/posts
    networks:
      - chatbot-network
    ports:
      - "5173:5173"
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

    

networks:
  chatbot-network:
    driver: overlay

volumes:
  mongo_data:
